# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='cpu_num',
            field=models.IntegerField(verbose_name='cpu核数'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='disk',
            field=models.CharField(max_length=4, verbose_name='磁盘容量'),
        ),
    ]
