# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181028_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='create_time',
            new_name='creat_time',
        ),
    ]
