# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='姓名')),
                ('sex', models.IntegerField(max_length=20, verbose_name='性别')),
                ('age', models.CharField(max_length=100, verbose_name='年龄')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['pk', 'username'],
            },
        ),
    ]
