# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='hostname',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='主机名'),
        ),
    ]
