# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181103_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='cpu_num',
            field=models.IntegerField(max_length=10, verbose_name='cpu核数'),
        ),
    ]
