# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='disk',
            field=models.CharField(default='1', max_length=4, verbose_name='磁盘大小'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='frame',
            field=models.CharField(default='222', max_length=32, verbose_name='机架'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='op',
            field=models.CharField(default='', max_length=32, verbose_name='运维负责人'),
        ),
        migrations.AddField(
            model_name='assets',
            name='os_system',
            field=models.CharField(default='q', max_length=32, verbose_name='操作系统'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='private_ip',
            field=models.CharField(default='q', max_length=32, verbose_name='私有ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='public_ip',
            field=models.CharField(default='', max_length=32, verbose_name='公网ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='assets',
            name='remote_ip',
            field=models.CharField(default='', max_length=32, verbose_name='远程ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='service_line',
            field=models.CharField(default='12', max_length=32, verbose_name='所属业务线'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.IntegerField(default='12', verbose_name='机器的状态0 | 1'),
            preserve_default=False,
        ),
    ]
