# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181028_0739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assets',
            table='assets',
        ),
    ]
