# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181111_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2018-11-11 12:05:00', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
