# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('logname', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='日志名称')),
                ('loglevel', models.CharField(default='', max_length=128, verbose_name='日志等级')),
                ('count', models.IntegerField(default=0, verbose_name='日志数量')),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
