# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logname',
            field=models.CharField(db_index=True, max_length=64, verbose_name='日志名称'),
        ),
    ]
