# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('desc', models.TextField(verbose_name='个人介绍')),
                ('create_time', models.DateTimeField(editable=False)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
