# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[[0, 'man'], [1, 'woman']], default=0, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('address', models.TextField(max_length=100, verbose_name='地址')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
    ]
