# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assetsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='主机名')),
                ('cpu_num', models.IntegerField(verbose_name='cpu核数')),
                ('cpu_model', models.CharField(max_length=100, verbose_name='cpu型号')),
                ('mem_total', models.CharField(default='8G', max_length=3, verbose_name='内存')),
                ('disk', models.CharField(max_length=4, verbose_name='磁盘大小')),
                ('public_ip', models.CharField(default='', max_length=32, verbose_name='公网ip')),
                ('private_ip', models.CharField(max_length=32, verbose_name='私有ip')),
                ('status', models.IntegerField(choices=[(0, '关机'), (1, '运行')], verbose_name='机器状态0 | 1')),
                ('os_system', models.CharField(max_length=32, verbose_name='操作系统')),
                ('service_line', models.CharField(max_length=32, verbose_name='所属业务线')),
                ('op', models.CharField(default='', max_length=32, verbose_name='运维负责人')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
