# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181028_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='cpu_model',
            field=models.CharField(default='', max_length=128, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cpu_num',
            field=models.IntegerField(default=1, verbose_name='CPU核数'),
        ),
    ]
