# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181028_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='disk',
            field=models.CharField(default='120G', max_length=4, verbose_name='磁盘大小'),
        ),
        migrations.AddField(
            model_name='assets',
            name='frame',
            field=models.CharField(default='', max_length=32, verbose_name='机架'),
        ),
        migrations.AddField(
            model_name='assets',
            name='mem_total',
            field=models.CharField(default='8G', max_length=3, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='assets',
            name='op',
            field=models.CharField(default='', max_length=32, verbose_name='运维负责人'),
        ),
        migrations.AddField(
            model_name='assets',
            name='os_system',
            field=models.CharField(default='', max_length=32, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='assets',
            name='private_ip',
            field=models.CharField(default='', max_length=32, verbose_name='私有ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='public_ip',
            field=models.CharField(default='', max_length=32, verbose_name='公网ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='remote_ip',
            field=models.CharField(default='', max_length=32, verbose_name='远程ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='service_line',
            field=models.CharField(default='', max_length=32, verbose_name='所属业务线'),
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.IntegerField(default=1, verbose_name='机器的状态0 | 1'),
        ),
    ]
