# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181028_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='disk',
            field=models.CharField(default=100, max_length=4, verbose_name='cipandaxiao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='mem_total',
            field=models.CharField(default='8g', max_length=3, verbose_name='neicun'),
        ),
        migrations.AddField(
            model_name='assets',
            name='public_ip',
            field=models.CharField(default='123.456.789.145', max_length=32, verbose_name='public ip'),
            preserve_default=False,
        ),
    ]
