# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181028_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='frame',
            field=models.CharField(default='a1', max_length=32, verbose_name='jijia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='op',
            field=models.CharField(default='', max_length=32, verbose_name='aa '),
        ),
        migrations.AddField(
            model_name='assets',
            name='os_system',
            field=models.CharField(default='CENTOS', max_length=32, verbose_name='os'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='private_ip',
            field=models.CharField(default='192.168.0.1', max_length=32, verbose_name='priviate ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='remote_ip',
            field=models.CharField(default='', max_length=32, verbose_name='remote ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='service_line',
            field=models.CharField(default='APP', max_length=32, verbose_name='group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.IntegerField(default=1, verbose_name='status 0 | 1'),
            preserve_default=False,
        ),
    ]
