# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181028_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='cpu_model',
            field=models.CharField(default='', max_length=100, verbose_name='cpu型号'),
        ),
        migrations.AddField(
            model_name='assets',
            name='cpu_num',
            field=models.IntegerField(default=0, verbose_name='cpu核数'),
        ),
        migrations.AddField(
            model_name='assets',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='hostname',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, verbose_name='主机名'),
        ),
    ]
