# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181028_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='create_time',
            field=models.DateTimeField(default='1970-01-01 09:00:00', verbose_name='创建时间'),
        ),
    ]
