# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='cpu_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='cpu核'),
        ),
    ]
